# Generated by Django 3.1.6 on 2021-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('room', models.TextField(max_length=250, null=True)),
                ('number', models.TextField(max_length=10, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
