# Generated by Django 3.1.6 on 2021-04-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Reserve',
        ),
    ]
