# Generated by Django 3.1.6 on 2021-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
