# Generated by Django 3.1.6 on 2021-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210416_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='number',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='room',
        ),
        migrations.AddField(
            model_name='reserve',
            name='roomcode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
