# Generated by Django 3.1.6 on 2021-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_room_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('room', models.TextField(max_length=200, null=True)),
                ('number', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
