# Generated by Django 3.1.6 on 2021-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210416_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
