# Generated by Django 3.1.6 on 2021-04-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
