# Generated by Django 3.1.6 on 2021-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_room_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
