# Generated by Django 3.1.6 on 2021-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210418_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
