# Generated by Django 4.0.4 on 2022-04-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_contact'),
        ('user', '0009_auto_20210420_1449'),
    ]

    operations = [
    ]
